/* VERIFICAR TODOS OS BDS DO SGBD*/
SHOW DATABASES;

/* VERIFICAR EM QUAL BD ESTOU*/
STATUS

CREATE DATABASE LIVRARIA;

USE LIVRARIA;

CREATE TABLE LIVROS (
    LIVRO VARCHAR(50),
    AUTOR VARCHAR(70),
    SEXO CHAR(1),
    PAGINAS INT(3),
    EDITORA VARCHAR(50),
    VALOR FLOAT(5,2),
    UF_EDITORA CHAR(2),
    ANO_PUBLICACAO CHAR(4)
);

INSERT INTO LIVROS (LIVRO, AUTOR, SEXO, PAGINAS, EDITORA, VALOR, 
UF_EDITORA, ANO_PUBLICACAO) 
VALUES ('CAVALEIRO REAL', 'ANA CLAÚDIA', 'F', 465, 'ATLAS', 49.90, 'RJ', '2009'),
       ('SQL PARA LEIGOS', 'JOÃO NUNES', 'M', 450, 'ADDISON', 98.00, 'SP', '2018'),
       ('RECEITAS CASEIRAS', 'CELIA TAVARES', 'F', 210, 'ATLAS', 45.00, 'RJ', '2008'),
       ('PESSOAS EFETIVAS', 'EDUARDO SANTOS', 'M', 390, 'BETA', 78.99, 'RJ', '2018'),
       ('HABITOS SAUDÁVEIS', 'EDUARDO SANTOS', 'M', 630, 'BETA', 150.98, 'RJ', '2019'),
       ('A CASA MARROM', 'HERMES MACEDO', 'M', 250, 'BUBBA', 60.00, 'MG', '2016'),
       ('ESTACIO QUERIDO', 'GERALDO FRANCISCO', 'M', 310, 'INSIGNIA', 100.00, 'ES', '2015'),
       ('PRA SEMPRE AMIGAS', 'LEDA SILVA', 'F', 510, 'INSIGNIA', 78.98, 'ES', '2011'),
       ('COPAS INESQUECÍVEIS', 'MARCO ALCANTARA', 'M', 200, 'LARSON', 130.98, 'RS', '2018'),
       ('O PODER DA MENTE', 'CLARA MAFRA', 'F', 120, 'CONTINENTAL', 56.58, 'RS', '2017');
  
SELECT * FROM LIVROS;

SELECT LIVRO, EDITORA FROM LIVROS;

SELECT LIVRO, UF_EDITORA FROM LIVROS WHERE SEXO = 'M';

SELECT LIVRO, PAGINAS FROM LIVROS WHERE SEXO = 'F';

SELECT VALOR FROM LIVROS WHERE UF_EDITORA = 'SP';

SELECT AUTOR, SEXO FROM LIVROS 
WHERE UF_EDITORA = 'SP' OR  UF_EDITORA = 'RJ' AND SEXO = 'M';

SELECT AUTOR, SEXO, UF_EDITORA FROM LIVROS 
WHERE SEXO = 'M' AND (UF_EDITORA = 'SP' OR  UF_EDITORA = 'RJ');



